global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['localhost:3001']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9216']
